# Generated by Django 4.2.4 on 2023-09-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('content_image', models.ImageField(upload_to='static/image/')),
            ],
        ),
    ]
