# Generated by Django 3.0.5 on 2023-10-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20231006_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_image',
            field=models.ImageField(upload_to='content/'),
        ),
    ]
